package serpis.ad;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido"
    ,catalog="dbprueba"
)
public class Pedido {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
     private long id;
	@ManyToOne
	@JoinColumn(name="cliente")
     private Cliente cliente;
     private Calendar fecha = Calendar.getInstance(); //now
     private BigDecimal importe;
     //private Set<PedidoLinea> pedidolineas = new HashSet<PedidoLinea>(0);
     
     @OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, orphanRemoval = true)
     private List<PedidoLinea> pedidoLineas = new ArrayList<>();
     
     public PedidoLinea[] getPedidoLineas(){
    	 return pedidoLineas.toArray(new PedidoLinea[0]);
     }
     
     public void add(PedidoLinea pedidoLinea) {
    	 pedidoLineas.add(pedidoLinea);
    	 pedidoLinea.setPedido(this);
     }
     
     public void remove(PedidoLinea pedidoLinea) {
    	 pedidoLineas.remove(pedidoLinea);
    	 pedidoLinea.setPedido(null);
     }
	
     public Pedido(Cliente cliente, Calendar fecha) {
        this.cliente = cliente;
        this.fecha = fecha;
     }
    
     public Pedido(Cliente cliente, Calendar fecha, BigDecimal importe, List<PedidoLinea> pedidolineas) {
       this.cliente = cliente;
       this.fecha = fecha;
       this.importe = importe;
       this.pedidoLineas = pedidolineas;
     }
    
     public Pedido() {
		// TODO Auto-generated constructor stub
	 }

	@Column(name="id", unique=true, nullable=false)
    public void setId(Long id) {
        this.id = id;
    }
    
    public Long getId() {
        return this.id;
    }

    @ManyToOne
    @JoinColumn(name="cliente", nullable=false)
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    public Cliente getCliente() {
        return this.cliente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public void setFecha(Calendar fecha) {
        this.fecha = fecha;
    }
    
    public Calendar getFecha() {
        return this.fecha;
    }
    
    public BigDecimal getImporte() {
        importe = BigDecimal.ZERO;
        for(PedidoLinea pedidoLinea : pedidoLineas)
        	importe = importe.add(pedidoLinea.getImporte());
        return importe;
        
    }

    @Override
    public String toString(){
   
    	return String.format("[%s] %s %s %s", id, cliente.getNombre(), fecha.getTime(), importe);	
    }

}

