package serpis.ad;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido"
    ,catalog="dbprueba"
)
public class Pedido  implements java.io.Serializable {


     private Long id;
     private Cliente cliente;
     private Date fecha;
     private BigDecimal importe;
     private Set<PedidoLinea> pedidolineas = new HashSet<PedidoLinea>(0);

    public Pedido() {
    }

	
    public Pedido(Cliente cliente, Date fecha) {
        this.cliente = cliente;
        this.fecha = fecha;
    }
    public Pedido(Cliente cliente, Date fecha, BigDecimal importe, Set<PedidoLinea> pedidolineas) {
       this.cliente = cliente;
       this.fecha = fecha;
       this.importe = importe;
       this.pedidolineas = pedidolineas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="importe", precision=10)
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set<PedidoLinea> getPedidolineas() {
        return this.pedidolineas;
    }
    
    public void setPedidolineas(Set<PedidoLinea> pedidolineas) {
        this.pedidolineas = pedidolineas;
    }
    
    @Override
    public String toString(){
   
//    	return "ID : "+String.valueOf(this.getId())
//    		+"\nCliente : "+String.valueOf(this.getCliente())
//    		+"\nFecha : "+String.valueOf(this.getFecha())
//    		+"\nImporte : "+String.valueOf(this.getImporte())
//    		
//    		;
    	return String.format("%-5s%-15s%-15s%-15s", String.valueOf(this.getId()),
				String.valueOf(this.getCliente()),
				String.valueOf(this.getFecha()),
				String.valueOf(this.getImporte()));

    	
    	
    }





}

