package serpis.ad;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido"
    ,catalog="dbprueba"
)
public class Pedido  implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
     private long id;
     private Cliente cliente;
     private Calendar fecha = Calendar.getInstance(); //now
     private BigDecimal importe;
     //private Set<PedidoLinea> pedidolineas = new HashSet<PedidoLinea>(0);
     
     @OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, orphanRemoval = true)
     private List<PedidoLinea> pedidoLineas = new ArrayList<>();
     
     public List<PedidoLinea> getPedidoLineas(){
    	 return pedidoLineas;
     }

    public Pedido() {
    }
	
    public Pedido(Cliente cliente, Calendar fecha) {
        this.cliente = cliente;
        this.fecha = fecha;
    }
    
    public Pedido(Cliente cliente, Calendar fecha, BigDecimal importe, List<PedidoLinea> pedidolineas) {
       this.cliente = cliente;
       this.fecha = fecha;
       this.importe = importe;
       this.pedidoLineas = pedidolineas;
    }

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Calendar getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Calendar fecha) {
        this.fecha = fecha;
    }

    @Column(name="importe", precision=10)
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

    
    @Override
    public String toString(){
   
    	return String.format("[%s] %s %s %s", id, cliente.getNombre(), fecha.getTime(), importe);
    	
    }

}

